include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.config.dart, lib/**.gen.dart, lib/**.ast.gql.dart, lib/**.req.gql.dart, lib/**.data.gql.dart, lib/**.var.gql.dart, lib/**.gql.g.dart, lib/**.gql.dart, lib/**.schema.gql.dart]

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**

  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-single-widget-per-file
    - prefer_relative_imports
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_declarations
    - exhaustive_cases
    - avoid_empty_else
    - directives_ordering
    - constant_identifier_names
    - avoid_print
    - avoid_redundant_argument_values
    - join_return_with_assignment
    - avoid_unnecessary_containers